### ISSUE TITLE
Option to get file path autocomplteion only after typing ./

### ISSUE THREAD

**Issue by predragnikolic** [evandrocoan/AutoFileName#8]
Hello, 
Is there a way to get file path autocompletion only after typing `./`? 
Right now I get suggestion in places I don't want to, and I want to restrict it to appear only when I type `./`.

**Comment by evandrocoan** [comment]
@predragnikolic, did you figured out how to fix this?

**Comment by predragnikolic** [comment]
No, I didn't :-)

**Comment by evandrocoan** [comment]
Try the package: https://github.com/sagold/FuzzyFilePath

**Comment by predragnikolic** [comment]
Thanks, I will try it :-)
